version: '3.6'

services:
  postgres-source:
    image:  postgres:13
    hostname: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./prerequisites/postgres-source:/docker-entrypoint-initdb.d
    command:
      - "-c"
      - "wal_level=logical"

  spark:
    build:
      dockerfile: Dockerfile